name: install test
on: 
  push:
  workflow_dispatch:

jobs:
  show-env:
    
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@main
      - run: brew update
      - run: brew install softhsm
      - run: ./docker.sh install
      - run: ./docker.sh installCompose
      - run: docker-compose version
      - run: ./nodejs.sh install

