name: install test
on: 
  push:
  workflow_dispatch:

jobs:
  show-env:
    
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@main
      - run: brew update
      - run: brew install softhsm
      - run: ./apps/docker.sh install
      - run: docker compose version
      - run: ./language/nodejs.sh install

